/**:
  map_viewer_node:
    ros__parameters:
      # Topic names
      map_topic: "/map"
      cmd_vel_topic: "cmd_vel"
      scan_topic: "scan"
      battery_state_topic: "battery_state"
      plan_topic: "plan"  # Nav2 planner output
      goal_topic: "goal_pose"
      initial_pose_topic: "initialpose"
      nav_action_client_topic: "navigate_to_pose"
      
      # Frame names
      map_frame: "map"
      map_folder: "/home/linux/test_ws/src/web_test/maps"
      base_link_frame: "base_link"
      tf_prefix: ""

      # Velocities
      max_linear_velocity: 0.2
      max_angular_velocity: 0.2
      
      # Server configuration
      port: 8082
      
      # Launch Commands
      mapping_launch_cmd: "ros2 launch turtlebot3_cartographer cartographer.launch.py use_sim_time:=True"
      navigation_launch_cmd: "ros2 launch turtlebot3_navigation2 navigation2.launch.py use_sim_time:=True"
      default_map: "test_map1"
      auto_start_nav: false
      
      # .env file path (relative to package share or absolute)
      env_file_path: ""  # Leave empty to use package_dir/.env
